# Generated by Django 4.2.13 on 2024-05-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="registeredDomains",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=30)),
                ("company_Address", models.CharField(max_length=50)),
                ("admin_officer", models.CharField(max_length=30)),
                ("domain", models.CharField(max_length=30)),
                ("approved", models.BooleanField(default=False)),
            ],
        ),
    ]
