# Generated by Django 4.2.13 on 2024-05-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_registereddomains"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="user_Type",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
