# Generated by Django 4.2.13 on 2024-05-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0003_users_user_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=30)),
                ("PaymentReference", models.CharField(max_length=30)),
            ],
        ),
    ]
