# Generated by Django 4.2.13 on 2024-07-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homePage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("email", models.EmailField(max_length=254)),
                ("Phone", models.IntegerField()),
                ("subject", models.CharField(max_length=80)),
                ("enquiry_text", models.TextField()),
            ],
        ),
    ]
