# Generated by Django 4.2.13 on 2024-06-10 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Company_Admin", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="CompanyInfo",),
        migrations.DeleteModel(name="ListOfBookings",),
        migrations.DeleteModel(name="ListOfCommonSpaces",),
    ]
