# Generated by Django 4.2.13 on 2024-06-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Company_Admin", "0002_delete_companyinfo_delete_listofbookings_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=30)),
                ("timezone", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="ListOfBookings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placeid", models.IntegerField()),
                ("domain", models.CharField(max_length=30)),
                ("username", models.CharField(max_length=30)),
                ("bookingdate", models.DateField()),
                ("bookingday", models.CharField(max_length=10)),
                ("starttime", models.TimeField()),
                ("endtime", models.TimeField()),
                ("currentstatus", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="ListOfCommonSpaces",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=50)),
                ("availability", models.JSONField(default=dict)),
            ],
        ),
    ]
