# Generated by Django 4.2.13 on 2024-06-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Company_Admin", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListOfPastBookings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placeid", models.IntegerField()),
                ("domain", models.CharField(max_length=30)),
                ("username", models.CharField(max_length=30)),
                ("bookingdate", models.DateField()),
                ("bookingday", models.CharField(max_length=10)),
                ("starttime", models.TimeField()),
                ("endtime", models.TimeField()),
                ("currentstatus", models.CharField(max_length=30)),
            ],
        ),
    ]
