# Generated by Django 4.2.13 on 2024-06-11 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Company_Admin", "0004_listofpastbookings"),
    ]

    operations = [
        migrations.DeleteModel(name="ListOfCommonSpaces",),
    ]
