# Generated by Django 4.2.13 on 2024-06-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Company_Admin", "0005_delete_listofcommonspaces"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListOfCommonSpaces",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=30)),
                ("SpaceName", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=50)),
                ("Capacity", models.IntegerField()),
                ("availability", models.JSONField(default=dict)),
                ("ReservationRestrictions", models.CharField(max_length=50, null=True)),
                ("AdditionalFeatures", models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
