# Generated by Django 4.2.13 on 2024-06-22 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Company_Admin", "0006_listofcommonspaces"),
    ]

    operations = [
        migrations.DeleteModel(name="ListOfPastBookings",),
    ]
